Fix Docker Github Actions and Linting and formatting

diff --git a/.github/workflows/lint-and-format.yml b/.github/workflows/lint-and-format.yml
--- a/.github/workflows/lint-and-format.yml
+++ b/.github/workflows/lint-and-format.yml
@@ -2,42 +2,42 @@ name: Lint and Format
 
 on:
   push:
-    branches: [ "main", "staging" ]
+    branches: ['main', 'staging']
   pull_request:
-    branches: [ "main", "staging" ]
+    branches: ['main', 'staging']
 
 jobs:
   lint-and-format:
     runs-on: ubuntu-latest
-    
+
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: '20.x'
-        cache: 'npm'
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20.x'
+          cache: 'npm'
 
-    - name: Install dependencies
-      run: npm ci
+      - name: Install dependencies
+        run: npm ci
 
-    - name: Run ESLint
-      run: npm run lint
-      # Improve readability of failures in logs
-      continue-on-error: true
-      id: lint
+      - name: Run ESLint
+        run: npm run lint
+        # Improve readability of failures in logs
+        continue-on-error: true
+        id: lint
 
-    - name: Check Formatting
-      run: npm run format:check
-      continue-on-error: true
-      id: format
+      - name: Check Formatting
+        run: npm run format:check
+        continue-on-error: true
+        id: format
 
-    - name: Check Status
-      if: steps.lint.outcome == 'failure' || steps.format.outcome == 'failure'
-      run: |
-        echo "::error::Linting or Formatting checks failed!"
-        echo "Run 'npm run lint:fix' to fix linting issues."
-        echo "Run 'npm run format' to fix formatting issues."
-        exit 1
+      - name: Check Status
+        if: steps.lint.outcome == 'failure' || steps.format.outcome == 'failure'
+        run: |
+          echo "::error::Linting or Formatting checks failed!"
+          echo "Run 'npm run lint:fix' to fix linting issues."
+          echo "Run 'npm run format' to fix formatting issues."
+          exit 1
